version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "192.168.26.68:5672:5672"  # RabbitMQ main port
      - "192.168.26.68:15672:15672"  # RabbitMQ management plugin port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_logs:/var/log/rabbitmq

volumes:
  rabbitmq_data: