version: "3.9"
services:
  producer_app:
    build:
      context: ../
      dockerfile: docker/app/app.Dockerfile
      # args:
      #   SERVER_IP: ${SERVER_IP:-192.168.26.68}
    env_file:
      - .env
    environment:
      HOST_IP: ${HOST_IP:-192.168.26.68}
    image: ${COMPOSE_PROJECT_NAME}-app:${DOCKER_BUILD_MODE:-prod}-${DOCKER_BUILD_VERSION:-0}  # Image Name
    container_name: ${COMPOSE_PROJECT_NAME}-app      # Container Name
    tty: true
    restart: unless-stopped
    volumes:
      - /var/www/html/vendor/
      - ../codes:/var/www/html/
    ports:
      - "9004:9000"
    networks:
      - ar-network

  producer_web:
    build:
      context: ../
      dockerfile: docker/web/web.Dockerfile
      args:
        HOST_IP: ${HOST_IP:-192.168.26.68}
    restart: unless-stopped
    image: ${COMPOSE_PROJECT_NAME}-web:${DOCKER_BUILD_MODE:-prod}-${DOCKER_BUILD_VERSION:-0}  # Image Name
    container_name: ${COMPOSE_PROJECT_NAME}-web      # Container Name
    tty: true
    ports:
      - ${HTTP_PUBLISH_PORT}:80
    networks:
      - ar-network
    depends_on:
      - producer_app

networks:
  ar-network:
    external: true
    name: ar-network
